/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author 104935
 */
public class TelaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoLitrosCombustivel = new javax.swing.JTextField();
        TipoCombustivel = new javax.swing.JComboBox<>();
        CampoTotalAPagar = new javax.swing.JFormattedTextField();
        BotaoCalcular = new javax.swing.JToggleButton();
        TiuloLitrosCombustivel = new javax.swing.JLabel();
        TituloTotalAPagar = new javax.swing.JLabel();
        Veiculo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CampoLitrosCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoLitrosCombustivelActionPerformed(evt);
            }
        });

        TipoCombustivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Etanol", "Diesel" }));
        TipoCombustivel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TipoCombustivelItemStateChanged(evt);
            }
        });
        TipoCombustivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TipoCombustivelMouseClicked(evt);
            }
        });
        TipoCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoCombustivelActionPerformed(evt);
            }
        });

        CampoTotalAPagar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        CampoTotalAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTotalAPagarActionPerformed(evt);
            }
        });

        BotaoCalcular.setText("Calcular");
        BotaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCalcularActionPerformed(evt);
            }
        });

        TiuloLitrosCombustivel.setText("Litros comb.");

        TituloTotalAPagar.setText("Total a pagar");

        Veiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CITROEN", "FIAT", "FORD", "GM - CHEVROLET", "HONDA ", "HYUNDAI", "KIA", "NISSAN", "PEUGEOT", "RENAUT", "TOYOTA ", "VW - VOLKSWAGEN", "OUTROS" }));
        Veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeiculoActionPerformed(evt);
            }
        });

        jLabel1.setText("Combustível");

        jLabel2.setText("Veículo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TiuloLitrosCombustivel)
                                    .addComponent(CampoLitrosCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BotaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(TituloTotalAPagar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TipoCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TiuloLitrosCombustivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CampoLitrosCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TipoCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TituloTotalAPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoLitrosCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoLitrosCombustivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoLitrosCombustivelActionPerformed

    private void CampoTotalAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTotalAPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTotalAPagarActionPerformed

    private void BotaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCalcularActionPerformed

    private void TipoCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoCombustivelActionPerformed
        TipoCombustivel.removeAllItems();
        TipoCombustivel.addItem("Gasolina");
        TipoCombustivel.addItem("Etanol");
        TipoCombustivel.addItem("Diesel");
    }//GEN-LAST:event_TipoCombustivelActionPerformed

    private void VeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeiculoActionPerformed
        /*
        CITROEN
        FIAT
        FORD
        GM - CHEVROLET
        HONDA 
        HYUNDAI
        KIA
        NISSAN
        PEUGEOT
        RENAUT
        TOYOTA 
        VW - VOLKSWAGEN
        OUTROS

            */
        
        Veiculo.addItem("Chevrolet");
        //Veiculo.addItem("Fiat");
    }//GEN-LAST:event_VeiculoActionPerformed

    private void TipoCombustivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TipoCombustivelMouseClicked
        
    }//GEN-LAST:event_TipoCombustivelMouseClicked

    private void TipoCombustivelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TipoCombustivelItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoCombustivelItemStateChanged

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotaoCalcular;
    private javax.swing.JTextField CampoLitrosCombustivel;
    private javax.swing.JFormattedTextField CampoTotalAPagar;
    private javax.swing.JComboBox<String> TipoCombustivel;
    private javax.swing.JLabel TituloTotalAPagar;
    private javax.swing.JLabel TiuloLitrosCombustivel;
    private javax.swing.JComboBox<String> Veiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
